
services:
  mysql_db:
    image: mysql:latest   # 또는 mysql:8.4 등 명시적 버전
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: jang
      MYSQL_PASSWORD: jang1234
      MYSQL_DATABASE: jpa
      TZ: Asia/Seoul
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--init-connect=SET NAMES utf8mb4"
      ] 
    volumes:
      - mydata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   
    restart: always  # 서버 재시작 시 자동 실행 (선택 사항)

volumes:
  mydata:

